module "mysql" {
  source = "github.com/entercloudsuite/terraform-modules//mysql?ref=2.7-devel"
  name = "${var.name}"
  quantity = "${var.quantity}"
  external = "${var.external}"
  network_name = "${var.network_name}"
  sec_group = "${var.sec_group}"
  keypair = "${var.keypair}"
  private_ssh_key = "${var.private_ssh_key}"
  mysql_port = "${var.mysql_port}"
  mysql_datadir = "${var.mysql_datadir}"
  mysql_admin_name = "${var.mysql_admin_name}"
  mysql_admin_password = "${var.mysql_admin_password}"
  mysql_replica_user_name = "${var.mysql_replica_user_name}"
  mysql_replica_user_password = "${var.mysql_replica_user_password}"
  consul = "${var.consul}"
  consul_port = "${var.consul_port}"
  consul_datacenter = "${var.consul_datacenter}"
  orchestrator = "${var.name}-orchestrator.service.automium.consul"
  orchestrator_port = "${var.orchestrator_port}"
  orchestrator_user = "${var.orchestrator_user}"
  orchestrator_password = "${var.orchestrator_password}"
  orchestrator_cluster_name = "${var.name}"
}

module "mysql-bootstrap" {
  source = "github.com/entercloudsuite/terraform-modules//mysql?ref=2.7-devel"
  name = "${var.name}-bootstrap"
  quantity = "${var.bootstrap ? 1 : 0}"
  external = "${var.external}"
  network_name = "${var.network_name}"
  sec_group = "${var.sec_group}"
  keypair = "${var.keypair}"
  private_ssh_key = "${var.private_ssh_key}"
  bootstrap = "${var.bootstrap}"
  mysql_port = "${var.mysql_port}"
  mysql_datadir = "${var.mysql_datadir}"
  mysql_admin_name = "${var.mysql_admin_name}"
  mysql_admin_password = "${var.mysql_admin_password}"
  mysql_replica_user_name = "${var.mysql_replica_user_name}"
  mysql_replica_user_password = "${var.mysql_replica_user_password}"
  consul = "${var.consul}"
  consul_port = "${var.consul_port}"
  consul_datacenter = "${var.consul_datacenter}"
  orchestrator = "${var.name}-orchestrator-vip.service.automium.consul"
  orchestrator_port = "${var.orchestrator_port}"
  orchestrator_user = "${var.orchestrator_user}"
  orchestrator_password = "${var.orchestrator_password}"
  orchestrator_cluster_name = "${var.name}"
}

module "orchestrator" {
  source = "github.com/entercloudsuite/terraform-modules//orchestrator?ref=2.7-devel"
  name = "${var.name}-orchestrator"
  quantity = "${var.orchestrator_quantity}"
  external = "${var.external}"
  network_name = "${var.network_name}"
  sec_group = "${var.sec_group}"
  keypair = "${var.keypair}"
  orchestrator_ip = "${var.orchestrator_ip}"
  orchestrator_subnet = "${var.orchestrator_subnet}"
  orchestrator_port = "${var.orchestrator_port}" 
  orchestrator_virtual_router_id = "${var.orchestrator_virtual_router_id}"
  orchestrator_user = "${var.orchestrator_user}" 
  orchestrator_password = "${var.orchestrator_password}" 
  orchestrator_raft_enabled = "true"
  orchestrator_raft_data_dir = "/var/lib/orchestrator" 
  orchestrator_raft_default_port = "10008"
  orchestrator_raft_nodes = "[ '${var.name}-orchestrator-0.node.${var.consul_datacenter}.consul', '${var.name}-orchestrator-1.node.${var.consul_datacenter}.consul', '${var.name}-orchestrator-2.node.${var.consul_datacenter}.consul' ]" 
  consul = "${var.consul}" 
  consul_port = "${var.consul_port}" 
  consul_datacenter = "${var.consul_datacenter}" 
}
